### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by gfa** [redhat-performance/tuned#3]
Hello

I'm starting to package tuned for debian, i'd really love to package a release and not a git snapshot, could you guys cut a release from the master branch? i saw there is a branch 1.0, should i package that instead?

PS:
i found the old repo, but it says it should not be used. i found a tarball for 2.7.1 but i really want to package using git tags

thanks!

**Comment by gfa** [comment]
OK, i found out the branch 1.0 is deprecated...

i did pull from the fedorahosted repo the tags, can i safely assume the release tagged v2.7.1 there is consistent what i'll see latter here?

**Comment by jeremyeder** [comment]
Ahh, that's who you are (debian packager?).  Welcome!  Welcome!

@yarda is the maintainer, let's see what he thinks.

**Comment by balticer** [comment]
Hi,

any news about that? Would be awesome to get tags in here.

regards
Kai

**Comment by yarda** [comment]
Welcome debian packager :). We had to switch from fedorahosted.org because the service is shutting down. Sorry for the missing tags, it's my fault - I have forgotten to copy them from the old repo :). I will fix it.

Yes, the old repo is consistent with this repo (till it was abandoned). Couldn't you temporally use stable tarball release linked form http://www.tuned-project.org/? We are going to soon (in cca. month) release new stable Tuned version and the release will be handled through github.

**Comment by yarda** [comment]
It should be fixed now.

**Comment by yarda** [comment]
Sorry for delay, I have an issue with my github account and I haven't been receiving email notifications. I have managed it with the github support, so hopefully it will be OK :)

**Comment by balticer** [comment]
Hi,

The link is pointing to fedorahosted and it seems a dead link.

regards
Kai

**Comment by yarda** [comment]
Thanks for the report, the download link should be fixed now. Fedora infra retired the download server sooner than I expected.

**Comment by balticer** [comment]
Seems working. I think this is resolved. Thank you!

**Comment by yarda** [comment]
NP, or you can use the github releases, e.g. for 2.7.1:https://github.com/redhat-performance/tuned/releases/tag/v2.7.1
