### ISSUE TITLE
Gnome-shell - doesn't change Power Mode indicator

### ISSUE THREAD

**Issue by francoism90** [redhat-performance/tuned#689]
I'm running Fedora Silverblue 41 (beta) with Gnome 47 (stable).

To save power, I switch to powersave at night:

```bash
$ tuned-adm profile powersave
$ tuned-adm active
Current active profile: powersave
```

However this doesn't change the Gnome-shell indicator, which keeps stating 'Balanced' as Power Mode.

Is this a known bug/limitation?

Thanks

**Comment by zacikpa** [comment]
Thanks, @francoism90. This is a known limitation. We currently have #646 open, which would allow non-bijective mappings between PPD profiles and TuneD profiles. If that gets merged, this limitation would stay, since tuned-ppd would not be able to determine the active PPD profile given the active TuneD profile. If we decide not to go with the change, this can be resolved.

**Comment by francoism90** [comment]
@zacikpa Thanks for your answer. :)

What exactly is the GS Indicator doing at the moment? If one switches to a profile, does tuned change the profile to that?

**Comment by zacikpa** [comment]
Yes, but it's a bit more complicated. Gnome control center works with the original profile names from power-profiles-daemon, and these are mapped to TuneD profiles. You can find the mapping in `/etc/tuned/ppd.conf`.

**Comment by zacikpa** [comment]
The changes in #689 were redesigned, so the PR should resolve this when merged.
