### ISSUE TITLE
Possibility to overwrite/force an option for all profiles?

### ISSUE THREAD

**Issue by PatrickJosh** [redhat-performance/tuned#699]
Hi,

I'd like to force a specific option, namely `panel_power_savings=0`, for all profiles on on of my systems. However, I've failed to accomplish this so far. Is there any possibility to force that option without having to change every profile in which it is changed to something else than 0?

Thanks very much!

**Comment by yarda** [comment]
Hi, I think you could use post loaded profile, which will be automatically loaded on top of each profile:
- setup overlay profile adding `panel_power_savings=0`, e.g.:
```
# mkdir -p /etc/tuned/profiles/panel_power_savings
# cat > /etc/tuned/profiles/panel_power_savings/tuned.conf <<:EOF
[main]
[video]
panel_power_savings=0
:EOF
```
- make it the post loaded profile:
```
# echo panel_power_savings > /etc/tuned/post_loaded_profile
```

And don't forget that you have the post loaded profile, because it's loaded as the last profile and it will be impossible then to change the `panel_power_savings` in "normal" profiles until you disable your post loaded profile.

**Comment by PatrickJosh** [comment]
Hi,

thank you, I've just tried it, and it works! :smile:

Thanks again.
