### ISSUE TITLE
tuned should track firmware initiated changes to the platform_profiles

### ISSUE THREAD

**Issue by ocrete** [redhat-performance/tuned#710]
On my ThinkPad X1 Carbon, when I press Fn-L/M/H, the firmware changes the profile profile, and this is reflected in /sys/firmware/acpi/platform_profile. The old power-profiles-daemon would monitor this file and update its state based on it. It seems this is missing from tuned.

**Comment by ocrete** [comment]
As a user, I think that this would be the expected behaviour. Changing the profile through the keyboard shortcut should just change the whole tuned profile.

**Comment by zacikpa** [comment]
The functionality is now implemented as part of #669. However, I'd consider it "experimental" at this point since we have to differentiate between when the file is changed by TuneD vs. when changed by the keypress (which is more difficult than expected). We'll likely make the functionality disabled by default, at least initially.

It will be possible to easily enable it by adding a single line (e.g., `thinkpad_function_keys=True`) to `/etc/tuned/ppd.conf`.

**Comment by ocrete** [comment]
I though this didn't work.. But then I realized it wasn't enabled by default. I enabled it and now it works
